editAreaLoader.lang["ru"]={
new_document: "Новый пустой документ",
search_button: "Поиск и замена",
search_command: "Искать следующий / открыть панель поиска",
search: "Поиск",
replace: "Замена",
replace_command: "Заменить / открыть панель поиска",
find_next: "Найти следующее",
replace_all: "Заменить все",
reg_exp: "Регулярное выражение",
match_case: "Учитывать регистр",
not_found: "Не найдено.",
occurrence_replaced: "Вхождение заменено.",
search_field_empty: "Поле поиска пустое",
restart_search_at_begin: "Достигнут конец документа. Начинаю с начала.",
move_popup: "Переместить окно поиска",
font_size: "--Размер шрифта--",
go_to_line: "Перейти к строке",
go_to_line_prompt: "Перейти к строке номер:",
undo: "Отменить",
redo: "Вернуть",
change_smooth_selection: "Включить/отключить некоторые функции просмотра (более красиво, но больше использует процессор)",
highlight: "Переключить подсветку синтаксиса вкл./выкл.",
reset_highlight: "Восстановить подсветку (если разсинхронизирована от текста)",
word_wrap: "Переносить длинные строки",
help: "О программе",
save: "Сохранить",
load: "Загрузить",
line_abbr: "Стр",
char_abbr: "Симв",
position: "Позиция",
total: "Всего",
close_popup: "Закрыть всплывающее окно",
shortcuts: "Горячие клавиши",
add_tab: "Добавить табуляцию в текст",
remove_tab: "убрать табуляцию из текста",
about_notice: "Внимание: функция подсветки синтаксиса только для небольших текстов",
toggle: "Вкл/Выкл подсветку",
accesskey: "Горячая клавиша",
tab: "Tab",
shift: "Shift",
ctrl: "Ctrl",
esc: "Esc",
processing: "Обработка...",
fullscreen: "Полный экран",
syntax_selection: "--Синтаксис--",
close_tab: "Закрыть файл"
};
